# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rebello/TrabalhosCBD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rebello/TrabalhosCBD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rebello/TrabalhosCBD/CMakeFiles /home/rebello/TrabalhosCBD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rebello/TrabalhosCBD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lista_02-0.0.0

# Build rule for target.
Lista_02-0.0.0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lista_02-0.0.0
.PHONY : Lista_02-0.0.0

# fast build rule for target.
Lista_02-0.0.0/fast:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/build
.PHONY : Lista_02-0.0.0/fast

#=============================================================================
# Target rules for targets named vhdf

# Build rule for target.
vhdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vhdf
.PHONY : vhdf

# fast build rule for target.
vhdf/fast:
	$(MAKE) -f lib/vhdf-1.0.0/CMakeFiles/vhdf.dir/build.make lib/vhdf-1.0.0/CMakeFiles/vhdf.dir/build
.PHONY : vhdf/fast

src/BlockIO.o: src/BlockIO.cpp.o

.PHONY : src/BlockIO.o

# target to build an object file
src/BlockIO.cpp.o:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/BlockIO.cpp.o
.PHONY : src/BlockIO.cpp.o

src/BlockIO.i: src/BlockIO.cpp.i

.PHONY : src/BlockIO.i

# target to preprocess a source file
src/BlockIO.cpp.i:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/BlockIO.cpp.i
.PHONY : src/BlockIO.cpp.i

src/BlockIO.s: src/BlockIO.cpp.s

.PHONY : src/BlockIO.s

# target to generate assembly for a file
src/BlockIO.cpp.s:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/BlockIO.cpp.s
.PHONY : src/BlockIO.cpp.s

src/Data.o: src/Data.cpp.o

.PHONY : src/Data.o

# target to build an object file
src/Data.cpp.o:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Data.cpp.o
.PHONY : src/Data.cpp.o

src/Data.i: src/Data.cpp.i

.PHONY : src/Data.i

# target to preprocess a source file
src/Data.cpp.i:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Data.cpp.i
.PHONY : src/Data.cpp.i

src/Data.s: src/Data.cpp.s

.PHONY : src/Data.s

# target to generate assembly for a file
src/Data.cpp.s:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Data.cpp.s
.PHONY : src/Data.cpp.s

src/Parser.o: src/Parser.cpp.o

.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i

.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s

.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Registro.o: src/Registro.cpp.o

.PHONY : src/Registro.o

# target to build an object file
src/Registro.cpp.o:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Registro.cpp.o
.PHONY : src/Registro.cpp.o

src/Registro.i: src/Registro.cpp.i

.PHONY : src/Registro.i

# target to preprocess a source file
src/Registro.cpp.i:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Registro.cpp.i
.PHONY : src/Registro.cpp.i

src/Registro.s: src/Registro.cpp.s

.PHONY : src/Registro.s

# target to generate assembly for a file
src/Registro.cpp.s:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Registro.cpp.s
.PHONY : src/Registro.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Lista_02-0.0.0.dir/build.make CMakeFiles/Lista_02-0.0.0.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... Lista_02-0.0.0"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... vhdf"
	@echo "... src/BlockIO.o"
	@echo "... src/BlockIO.i"
	@echo "... src/BlockIO.s"
	@echo "... src/Data.o"
	@echo "... src/Data.i"
	@echo "... src/Data.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Registro.o"
	@echo "... src/Registro.i"
	@echo "... src/Registro.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

